jenkins:
  systemMessage: "CloudForge AI: CD pipeline"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
unclassified:
  location:
    url: http://localhost:8080/
jobs:
  - script: >
      pipelineJob('cloudforge') {
        definition {
          cpsScm {
            scm {
              git {
                remote { url('https://github.com/LakshyaBetala/news_analyzer.git') }
                branch('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
